### ISSUE TITLE
android.content.res.Resources$NotFoundException: 

### ISSUE THREAD

**Issue by karopass** [geniusforapp/fancyDialog#9]
Hi ! I am facing above issue in my application for use custom imageresource.
I have used like this 

 FancyAlertDialog.Builder alert = new FancyAlertDialog.Builder(Splash.this)
                //.setImageDrawable
                .setImageRecourse(R.drawable.error)
                .setTextTitle("OH NO")
                .setTextSubTitle("NETWORK ERROR")
                .setBodyColor(R.color.white)
                .setBackgroundColor(R.color.image_back)
                .setTitleColor(R.color.colorAccent)
                .setSubtitleColor(R.color.yello)
                .setBody("There Something wrong to connect server. Please connect internet or try later")
                .setNegativeColor(R.color.red)
                .setNegativeButtonText("Exit")

But getting error in android 6.0.0
called android.content.res.Resources$NotFoundException: File res/drawable/error.png from xml type xml resource ID #0x7f020072. How can I solve it ? My build version is 25.0.0. Thanks

**Comment by geniusforapp** [comment]
if you wan to use vector please use .setImageRecourse(R.drawable.error) or normal png 
.setImageDrawable(getResources().getDrawable(R.drawable.ic_cloud_computing))
use this will fix it
